#!/usr/bin/env node

// GRUNT-GITHOOKS START
var exec = require('child_process').exec;

exec('grunt jsdoc2md:docs', function (err, stdout, stderr) {

  console.log(stdout);

  var exitCode = 0;
  if (err) {
    console.log(stderr);
    exitCode = -1;
  }

  exec('git add api/*', function (err, stdout, stderr) {
    console.log(stdout);

    var exitCode = 0;
    if (err) {
      console.log(stderr);
      exitCode = -1;
    }
    process.exit(exitCode);
  });

});



// GRUNT-GITHOOKS END